module.exports = {
  CLAIM_PLAYER: 'CLAIM_PLAYER',
  PLAYER_CLAIMED: 'PLAYER_CLAIMED',
  PLAYER_READY: 'PLAYER_READY',
  MOVE_LEFT: 'MOVE_LEFT',
  MOVE_RIGHT: 'MOVE_RIGHT',
  ATTACK: 'ATTACK',
  FACING_RIGHT: 'FACING_RIGHT',
  FACING_LEFT: 'FACING_LEFT',
  STOP: 'STOP',
  START_GAME: 'START_GAME',
  CLAIM_GAME_HOST: 'CLAIM_GAME_HOST',
  PLAYER_LEAVE: 'PLAYER_LEAVE',
  CHECK_PLAYER_AVAILABLE: 'CHECK_PLAYER_AVAILABLE',
  SEND_PLAYER_AVAILABILITY: 'SEND_PLAYER_AVAILABILITY'
}