module.exports = {
  PLAYER_READY: 'PLAYER_READY',
  CLAIM_GAME_HOST: 'CLAIM_GAME_HOST',
  PLAYER_LEAVE: 'PLAYER_LEAVE',
  CHECK_PLAYER_AVAILABLE: 'CHECK_PLAYER_AVAILABLE',
  SEND_PLAYER_AVAILABILITY: 'SEND_PLAYER_AVAILABILITY'
}